
-- Add new columns to warehouses table
ALTER TABLE warehouses 
ADD COLUMN IF NOT EXISTS type VARCHAR(20) DEFAULT 'STORE',
ADD COLUMN IF NOT EXISTS capacity NUMERIC(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS manager_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS contact_email VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'OPERATIONAL';

-- Add comment on columns
COMMENT ON COLUMN warehouses.type IS 'Type of warehouse: MAIN, STORE, SHOWROOM, TRANSIT, DAMAGED';
COMMENT ON COLUMN warehouses.status IS 'Operational status: OPERATIONAL, MAINTENANCE, CLOSED';
